
# Netlify configuration file

[build]
  # Directory to publish (the output of the build)
  publish = "dist"
  # Build command
  command = "npm run build"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Set cache headers for assets
[[headers]]
  # Define headers for all assets
  for = "/assets/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000" # 1 year
